apiVersion: apps/v1
kind: Deployment
metadata:
  name: pacman-deployment
  labels:
    app: pacman-app
spec:
  replicas: 6
  template:
    metadata:
      labels:
        app: pacman
    spec:
      containers:
      - name: pacman
        image: vanvoo/pacman
        ports:
        - containerPort: 8080
