apiVersion: v1
kind: Pod
metadata:
  name: pacman
spec:
  containers:
    - name: pacman
      image: index.docker.io/vanvoo/pacman:latest
      imagePullPolicy: Always
      command: [ "echo", "SUCCESS" ]
